name: IMDb Watch History

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          pip install playwright
          playwright install --with-deps

      - run: python scrape_imdb.py

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "update imdb" || exit 0
          git push
